
version: '3.9'

services:
  db:
    container_name: moviesite
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: movies_db
    ports:
      - "3306:3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"