INSERT INTO gender (gender_name) VALUES ('male');
INSERT INTO gender (gender_name) VALUES ('female');

INSERT INTO user_role (authority) VALUES ('USER');
INSERT INTO user_role (authority) VALUES ('MODERATOR');
INSERT INTO user_role (authority) VALUES ('ADMIN');

INSERT INTO movie_genre (movie_genre_name) VALUES ('Horror');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Scientist');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Animation');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Adventure');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Thriller');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Comedy');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Drama');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Action');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Wars');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Crime');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Fantasy');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Mystery');
INSERT INTO movie_genre (movie_genre_name) VALUES ('Anime');

INSERT INTO director (director_name) VALUES ('James Wan');
INSERT INTO director (director_name) VALUES ('Justin Lin');
INSERT INTO director (director_name) VALUES ('Steven Spielberg');
INSERT INTO director (director_name) VALUES ('Alfred Hitchcock');
INSERT INTO director (director_name) VALUES ('Orson Welles');
INSERT INTO director (director_name) VALUES ('John Ford');
INSERT INTO director (director_name) VALUES ('Howard Hawks');
INSERT INTO director (director_name) VALUES ('Buster Keaton');
INSERT INTO director (director_name) VALUES ('John Huston');
INSERT INTO director (director_name) VALUES ('Martin Scorsese');
INSERT INTO director (director_name) VALUES ('Paul Anderson');
INSERT INTO director (director_name) VALUES ('David Fincher');
INSERT INTO director (director_name) VALUES ('Alexander Payne');
INSERT INTO director (director_name) VALUES ('Ang Lee');
INSERT INTO director (director_name) VALUES ('Darren Aronofsky');
INSERT INTO director (director_name) VALUES ('David Cronenberg');
INSERT INTO director (director_name) VALUES ('Mike Leigh');
INSERT INTO director (director_name) VALUES ('Steven Soderbergh');
INSERT INTO director (director_name) VALUES ('Danny Boyle');
INSERT INTO director (director_name) VALUES ('Gus Van Sant');
INSERT INTO director (director_name) VALUES ('Stephen Frears');
INSERT INTO director (director_name) VALUES ('Werner Herzog');
INSERT INTO director (director_name) VALUES ('David Russell');
INSERT INTO director (director_name) VALUES ('Hayao Mizayaki');
INSERT INTO director (director_name) VALUES ('Todd Field');
INSERT INTO director (director_name) VALUES ('Fernando Meirelles');
INSERT INTO director (director_name) VALUES ('Steve McQueen');
INSERT INTO director (director_name) VALUES ('Ken Loach');
INSERT INTO director (director_name) VALUES ('Jafar Panahi');
INSERT INTO director (director_name) VALUES ('Tomas Alfredson');
INSERT INTO director (director_name) VALUES ('Todd Phillips');
INSERT INTO director (director_name) VALUES ('Sam Mendes');
INSERT INTO director (director_name) VALUES ('Jake Casdan');
INSERT INTO director (director_name) VALUES ('Rob Cohen');
INSERT INTO director (director_name) VALUES ('John Singleton');
INSERT INTO director (director_name) VALUES ('F. Gary Gray');
INSERT INTO director (director_name) VALUES ('Dan Scanlon');
INSERT INTO director (director_name) VALUES ('Harald Zwart');
INSERT INTO director (director_name) VALUES ('Michael Cristofer');

INSERT INTO actor (actor_name) VALUES ('Vin Diesel');
INSERT INTO actor (actor_name) VALUES ('The Rock');
INSERT INTO actor (actor_name) VALUES ('Tyrese Gibson');
INSERT INTO actor (actor_name) VALUES ('Jack Nicholson');
INSERT INTO actor (actor_name) VALUES ('Ralph Fiennes');
INSERT INTO actor (actor_name) VALUES ('Robert De Niro');
INSERT INTO actor (actor_name) VALUES ('Al Pacino');
INSERT INTO actor (actor_name) VALUES ('Dustin Hoffman');
INSERT INTO actor (actor_name) VALUES ('Tom Hanks');
INSERT INTO actor (actor_name) VALUES ('Brad Pitt');
INSERT INTO actor (actor_name) VALUES ('Anthony Hopkins');
INSERT INTO actor (actor_name) VALUES ('Jeremy Irons');
INSERT INTO actor (actor_name) VALUES ('Denzel Washington');
INSERT INTO actor (actor_name) VALUES ('Gene Hackman');
INSERT INTO actor (actor_name) VALUES ('Jeff Bridges');
INSERT INTO actor (actor_name) VALUES ('Tim Robbins');
INSERT INTO actor (actor_name) VALUES ('Kevin Costner');
INSERT INTO actor (actor_name) VALUES ('Leonardo DiCaprio');
INSERT INTO actor (actor_name) VALUES ('Mel Gibson');
INSERT INTO actor (actor_name) VALUES ('Robert Duvall');
INSERT INTO actor (actor_name) VALUES ('Samuel L. Jackson');
INSERT INTO actor (actor_name) VALUES ('Tommy Lee Jones');
INSERT INTO actor (actor_name) VALUES ('Kevin Spacey');
INSERT INTO actor (actor_name) VALUES ('Nicolas Cage');
INSERT INTO actor (actor_name) VALUES ('Morgan Freeman');
INSERT INTO actor (actor_name) VALUES ('Michael Caine');
INSERT INTO actor (actor_name) VALUES ('Bruce Willis');
INSERT INTO actor (actor_name) VALUES ('Johny Depp');
INSERT INTO actor (actor_name) VALUES ('Ben Kingsley');
INSERT INTO actor (actor_name) VALUES ('Tom Cruise');
INSERT INTO actor (actor_name) VALUES ('Heath Ledger');
INSERT INTO actor (actor_name) VALUES ('Philip Seymour Hoffman');
INSERT INTO actor (actor_name) VALUES ('John Malkovich');
INSERT INTO actor (actor_name) VALUES ('Christian Bale');
INSERT INTO actor (actor_name) VALUES ('Colin Firth');
INSERT INTO actor (actor_name) VALUES ('George Clooney');
INSERT INTO actor (actor_name) VALUES ('Edward Norton');
INSERT INTO actor (actor_name) VALUES ('Richard Gere');
INSERT INTO actor (actor_name) VALUES ('Gary Oldman');
INSERT INTO actor (actor_name) VALUES ('Harrison Ford');
INSERT INTO actor (actor_name) VALUES ('Matt Damon');
INSERT INTO actor (actor_name) VALUES ('Woody Harrelson');
INSERT INTO actor (actor_name) VALUES ('John Hurt');
INSERT INTO actor (actor_name) VALUES ('Sean Penn');
INSERT INTO actor (actor_name) VALUES ('Christopher Walken');
INSERT INTO actor (actor_name) VALUES ('Mickey Rourke');
INSERT INTO actor (actor_name) VALUES ('Michael Douglas');
INSERT INTO actor (actor_name) VALUES ('Forest Whitaker');
INSERT INTO actor (actor_name) VALUES ('Liam Neeson');
INSERT INTO actor (actor_name) VALUES ('Will Smith');
INSERT INTO actor (actor_name) VALUES ('Robin Williams');
INSERT INTO actor (actor_name) VALUES ('Keanu Reeves');
INSERT INTO actor (actor_name) VALUES ('Michael Madsen');
INSERT INTO actor (actor_name) VALUES ('Kevin Bacon');
INSERT INTO actor (actor_name) VALUES ('Ed Harris');
INSERT INTO actor (actor_name) VALUES ('Alain Delon');
INSERT INTO actor (actor_name) VALUES ('Gerard Depardieu');
INSERT INTO actor (actor_name) VALUES ('Val Kilmer');
INSERT INTO actor (actor_name) VALUES ('Jared Leto');
INSERT INTO actor (actor_name) VALUES ('Laurence Fishburne');
INSERT INTO actor (actor_name) VALUES ('Antonio Banderas');
INSERT INTO actor (actor_name) VALUES ('John Travolta');
INSERT INTO actor (actor_name) VALUES ('Arnold Schwarzenegger');
INSERT INTO actor (actor_name) VALUES ('Michael Keaton');
INSERT INTO actor (actor_name) VALUES ('Jude Law');
INSERT INTO actor (actor_name) VALUES ('Alec Baldwin');
INSERT INTO actor (actor_name) VALUES ('Javier Bardem');

INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 1', 2001, 34, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 2', 2003, 35, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 3 Tokyo Drift', 2006, 2, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 4', 2009, 2, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 5', 2011, 2, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 6', 2013, 2, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 7', 2015, 1, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 8', 2017, 36, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Fast and Furious 9', 2020, 2, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Jumanji', 2017, 33, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Onward', 2020, 37, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Karate Kid', 2010, 38, 0, 0);
INSERT INTO movie (movie_name, movie_year, movie_director_id, movie_views, movie_rating) VALUES ('Original Sin', 2001, 39, 0, 0);

INSERT INTO poster (poster_name, movie_id) VALUES ('Fast_One_Poster.jpg', 1);
INSERT INTO poster (poster_name, movie_id) VALUES ('f2.jpg', 2);
INSERT INTO poster (poster_name, movie_id) VALUES ('f3.jpg', 3);
INSERT INTO poster (poster_name, movie_id) VALUES ('f4.jpg', 4);
INSERT INTO poster (poster_name, movie_id) VALUES ('f5.jpg', 5);
INSERT INTO poster (poster_name, movie_id) VALUES ('f6.jpg', 6);
INSERT INTO poster (poster_name, movie_id) VALUES ('FF7_officialposter.jpg', 7);
INSERT INTO poster (poster_name, movie_id) VALUES ('f8.jpg', 8);
INSERT INTO poster (poster_name, movie_id) VALUES ('f9.jpg', 9);
INSERT INTO poster (poster_name, movie_id) VALUES ('jumanji.jpg', 10);
INSERT INTO poster (poster_name, movie_id) VALUES ('onward.jpg', 11);
INSERT INTO poster (poster_name, movie_id) VALUES ('karate-kid.jpg', 12);
INSERT INTO poster (poster_name, movie_id) VALUES ('original-sin.jpg', 13);
