INSERT INTO genders (gender_name) VALUES ('male');
INSERT INTO genders (gender_name) VALUES ('female');

INSERT INTO user_roles (authority) VALUES ('USER');
INSERT INTO user_roles (authority) VALUES ('MODERATOR');
INSERT INTO user_roles (authority) VALUES ('ADMIN');

INSERT INTO movietype (movietype_label) VALUES ('Horror');
INSERT INTO movietype (movietype_label) VALUES ('Scientist');
INSERT INTO movietype (movietype_label) VALUES ('Animation');
INSERT INTO movietype (movietype_label) VALUES ('Adventure');
INSERT INTO movietype (movietype_label) VALUES ('Thriller');
INSERT INTO movietype (movietype_label) VALUES ('Comedy');
INSERT INTO movietype (movietype_label) VALUES ('Drama');
INSERT INTO movietype (movietype_label) VALUES ('Action');
INSERT INTO movietype (movietype_label) VALUES ('Wars');
INSERT INTO movietype (movietype_label) VALUES ('Crime');
INSERT INTO movietype (movietype_label) VALUES ('Fantasy');
INSERT INTO movietype (movietype_label) VALUES ('Mystery');

INSERT INTO directors (director_name) VALUES ('James Wan');
INSERT INTO directors (director_name) VALUES ('Justin Lin');
INSERT INTO directors (director_name) VALUES ('Steven Spielberg');
INSERT INTO directors (director_name) VALUES ('Alfred Hitchcock');
INSERT INTO directors (director_name) VALUES ('Orson Welles');
INSERT INTO directors (director_name) VALUES ('John Ford');
INSERT INTO directors (director_name) VALUES ('Howard Hawks');
INSERT INTO directors (director_name) VALUES ('Buster Keaton');
INSERT INTO directors (director_name) VALUES ('John Huston');
INSERT INTO directors (director_name) VALUES ('Martin Scorsese');
INSERT INTO directors (director_name) VALUES ('Paul Anderson');
INSERT INTO directors (director_name) VALUES ('David Fincher');
INSERT INTO directors (director_name) VALUES ('Alexander Payne');
INSERT INTO directors (director_name) VALUES ('Ang Lee');
INSERT INTO directors (director_name) VALUES ('Darren Aronofsky');
INSERT INTO directors (director_name) VALUES ('David Cronenberg');
INSERT INTO directors (director_name) VALUES ('Mike Leigh');
INSERT INTO directors (director_name) VALUES ('Steven Soderbergh');
INSERT INTO directors (director_name) VALUES ('Danny Boyle');
INSERT INTO directors (director_name) VALUES ('Gus Van Sant');
INSERT INTO directors (director_name) VALUES ('Stephen Frears');
INSERT INTO directors (director_name) VALUES ('Werner Herzog');
INSERT INTO directors (director_name) VALUES ('David Russell');
INSERT INTO directors (director_name) VALUES ('Hayao Mizayaki');
INSERT INTO directors (director_name) VALUES ('Todd Field');
INSERT INTO directors (director_name) VALUES ('Fernando Meirelles');
INSERT INTO directors (director_name) VALUES ('Steve McQueen');
INSERT INTO directors (director_name) VALUES ('Ken Loach');
INSERT INTO directors (director_name) VALUES ('Jafar Panahi');
INSERT INTO directors (director_name) VALUES ('Tomas Alfredson');
INSERT INTO directors (director_name) VALUES ('Todd Phillips');
INSERT INTO directors (director_name) VALUES ('Sam Mendes');

INSERT INTO actors (actor_name) VALUES ('Vin Diesel');
INSERT INTO actors (actor_name) VALUES ('The Rock');
INSERT INTO actors (actor_name) VALUES ('Tyrese Gibson');
INSERT INTO actors (actor_name) VALUES ('Jack Nicholson');
INSERT INTO actors (actor_name) VALUES ('Ralph Fiennes');
INSERT INTO actors (actor_name) VALUES ('Robert De Niro');
INSERT INTO actors (actor_name) VALUES ('Al Pacino');
INSERT INTO actors (actor_name) VALUES ('Dustin Hoffman');
INSERT INTO actors (actor_name) VALUES ('Tom Hanks');
INSERT INTO actors (actor_name) VALUES ('Brad Pitt');
INSERT INTO actors (actor_name) VALUES ('Anthony Hopkins');
INSERT INTO actors (actor_name) VALUES ('Jeremy Irons');
INSERT INTO actors (actor_name) VALUES ('Denzel Washington');
INSERT INTO actors (actor_name) VALUES ('Gene Hackman');
INSERT INTO actors (actor_name) VALUES ('Jeff Bridges');
INSERT INTO actors (actor_name) VALUES ('Tim Robbins');
INSERT INTO actors (actor_name) VALUES ('Kevin Costner');
INSERT INTO actors (actor_name) VALUES ('Leonardo DiCaprio');
INSERT INTO actors (actor_name) VALUES ('Mel Gibson');
INSERT INTO actors (actor_name) VALUES ('Robert Duvall');
INSERT INTO actors (actor_name) VALUES ('Samuel L. Jackson');
INSERT INTO actors (actor_name) VALUES ('Tommy Lee Jones');
INSERT INTO actors (actor_name) VALUES ('Kevin Spacey');
INSERT INTO actors (actor_name) VALUES ('Nicolas Cage');
INSERT INTO actors (actor_name) VALUES ('Morgan Freeman');
INSERT INTO actors (actor_name) VALUES ('Michael Caine');
INSERT INTO actors (actor_name) VALUES ('Bruce Willis');
INSERT INTO actors (actor_name) VALUES ('Johny Depp');
INSERT INTO actors (actor_name) VALUES ('Ben Kingsley');
INSERT INTO actors (actor_name) VALUES ('Tom Cruise');
INSERT INTO actors (actor_name) VALUES ('Heath Ledger');
INSERT INTO actors (actor_name) VALUES ('Philip Seymour Hoffman');
INSERT INTO actors (actor_name) VALUES ('John Malkovich');
INSERT INTO actors (actor_name) VALUES ('Christian Bale');
INSERT INTO actors (actor_name) VALUES ('Colin Firth');
INSERT INTO actors (actor_name) VALUES ('George Clooney');
INSERT INTO actors (actor_name) VALUES ('Edward Norton');
INSERT INTO actors (actor_name) VALUES ('Richard Gere');
INSERT INTO actors (actor_name) VALUES ('Gary Oldman');
INSERT INTO actors (actor_name) VALUES ('Harrison Ford');
INSERT INTO actors (actor_name) VALUES ('Matt Damon');
INSERT INTO actors (actor_name) VALUES ('Woody Harrelson');
INSERT INTO actors (actor_name) VALUES ('John Hurt');
INSERT INTO actors (actor_name) VALUES ('Sean Penn');
INSERT INTO actors (actor_name) VALUES ('Christopher Walken');
INSERT INTO actors (actor_name) VALUES ('Mickey Rourke');
INSERT INTO actors (actor_name) VALUES ('Michael Douglas');
INSERT INTO actors (actor_name) VALUES ('Forest Whitaker');
INSERT INTO actors (actor_name) VALUES ('Liam Neeson');
INSERT INTO actors (actor_name) VALUES ('Will Smith');
INSERT INTO actors (actor_name) VALUES ('Robin Williams');
INSERT INTO actors (actor_name) VALUES ('Keanu Reeves');
INSERT INTO actors (actor_name) VALUES ('Michael Madsen');
INSERT INTO actors (actor_name) VALUES ('Kevin Bacon');
INSERT INTO actors (actor_name) VALUES ('Ed Harris');
INSERT INTO actors (actor_name) VALUES ('Alain Delon');
INSERT INTO actors (actor_name) VALUES ('Gerard Depardieu');
INSERT INTO actors (actor_name) VALUES ('Val Kilmer');
INSERT INTO actors (actor_name) VALUES ('Jared Leto');
INSERT INTO actors (actor_name) VALUES ('Laurence Fishburne');
INSERT INTO actors (actor_name) VALUES ('Antonio Banderas');
INSERT INTO actors (actor_name) VALUES ('John Travolta');
INSERT INTO actors (actor_name) VALUES ('Arnold Schwarzenegger');
INSERT INTO actors (actor_name) VALUES ('Michael Keaton');
INSERT INTO actors (actor_name) VALUES ('Jude Law');
INSERT INTO actors (actor_name) VALUES ('Alec Baldwin');
INSERT INTO actors (actor_name) VALUES ('Javier Bardem');

INSERT INTO movie (movie_name, movie_running_time, movie_year, movie_director_id) VALUES ('Fast and Furious 7', 0, 2015, 1);
INSERT INTO movie (movie_name, movie_running_time, movie_year, movie_director_id) VALUES ('Fast and Furious 6', 0, 2013, 2);

INSERT INTO movie_images (movie_image_name, movie_id) VALUES ('recived_0274812', 1);
INSERT INTO movie_images (movie_image_name, movie_id) VALUES ('recived_0274222', 2);